import { DOCUMENT, inject, Injectable, REQUEST } from '@angular/core';
import { Meta, Title } from '@angular/platform-browser';
import { SeoData } from '../utils/seo-model';
import { Router } from '@angular/router';

@Injectable({
  providedIn: 'root',
})
export class SeoManager {
  title = inject(Title);
  meta = inject(Meta);
  router = inject(Router);
  request = inject(REQUEST, { optional: true });
  document = inject(DOCUMENT);

  private readonly siteName = 'Medi-Ray';
  private readonly defaultDescription = 'Medi-Ray is your go-to platform for managing medical records efficiently and securely.';
  private readonly defaultImage = 'https://www.dummyimage.com/600x400/000/fff&text=Medi-Ray';

  updateSeoData(seoData: SeoData) {
    this.title.setTitle(seoData.title + ' | ' + this.siteName);
    this.meta.updateTag({ name: 'description', content: seoData.description || this.defaultDescription });
    if (seoData.image) {
      this.meta.updateTag({ property: 'og:image', content: seoData.image });
    }
    if (seoData.type) {
      this.meta.updateTag({ property: 'og:type', content: seoData.type });
    }

    let origin = '';
    if (this.request) {
      const headers = this.request.headers as Headers | undefined;
      const protocol = (headers?.get('x-forwarded-proto') || this.request.url.split(':')[0] || 'http') + '://'
      // Use x-forwarded-host for correct host behind proxies
      const host = headers?.get('x-forwarded-host') || headers?.get('host') || '';
      origin = host ? protocol + host : '';
    } else if (typeof window !== 'undefined') {
      origin = window.location.origin;
    }
    const fullUrl = origin + this.router.url;

    let canonicalLink = this.document.querySelector("link[rel='canonical']") as HTMLLinkElement | null;
    if (!canonicalLink) {
      canonicalLink = this.document.createElement('link');
      canonicalLink.setAttribute('rel', 'canonical');
      this.document.head.appendChild(canonicalLink);
    }
    canonicalLink.setAttribute('href', fullUrl);

    this.meta.updateTag({ property: 'og:type', content: seoData.type || 'website' });
    this.meta.updateTag({ property: 'og:site_name', content: this.siteName });
    this.meta.updateTag({ property: 'og:title', content: seoData.title });
    this.meta.updateTag({ property: 'og:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'og:url', content: fullUrl });
    this.meta.updateTag({ property: 'og:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'og:image:width', content: '600' });
    this.meta.updateTag({ property: 'og:image:height', content: '400' });
    this.meta.updateTag({ property: 'og:image:alt', content: seoData.title });
    this.meta.updateTag({ property: 'og:locale', content: 'en_US' });

    this.meta.updateTag({ property: 'twitter:creator', content: '@MediRay' });
    this.meta.updateTag({ property: 'twitter:author', content: '@MediRay' });
    this.meta.updateTag({ property: 'twitter:domain', content: this.siteName });
    this.meta.updateTag({ property: 'twitter:url', content: fullUrl });
    this.meta.updateTag({ property: 'twitter:publisher', content: '@MediRay' });
    this.meta.updateTag({ property: 'twitter:site', content: '@MediRay' });
    this.meta.updateTag({ property: 'twitter:card', content: 'summary_large_image' });
    this.meta.updateTag({ property: 'twitter:title', content: seoData.title });
    this.meta.updateTag({ property: 'twitter:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'twitter:image', content: seoData.image || this.defaultImage });

    this.meta.updateTag({ property: 'viewport', content: 'width=device-width, initial-scale=1' });
    this.meta.updateTag({ property: 'robots', content: 'index, follow' });
    this.meta.updateTag({ property: 'googlebot', content: 'index, follow' });
    this.meta.updateTag({ property: 'bingbot', content: 'index, follow' });
    this.meta.updateTag({ property: 'yandexbot', content: 'index, follow' });
    this.meta.updateTag({ property: 'msnbot', content: 'index, follow' });
    this.meta.updateTag({ property: 'google-site-verification', content: 'your-google-site-verification-code' });
    this.meta.updateTag({ property: 'bing-site-verification', content: 'your-bing-site-verification-code' });
    this.meta.updateTag({ property: 'yandex-site-verification', content: 'your-yandex-site-verification-code' });
    this.meta.updateTag({ property: 'apple-mobile-web-app-title', content: this.siteName });
    this.meta.updateTag({ property: 'application-name', content: this.siteName });
    this.meta.updateTag({ property: 'facebook:title', content: seoData.title });
    this.meta.updateTag({ property: 'facebook:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'facebook:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'linkedin:title', content: seoData.title });
    this.meta.updateTag({ property: 'linkedin:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'linkedin:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'pinterest:title', content: seoData.title });
    this.meta.updateTag({ property: 'pinterest:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'pinterest:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'telegram:title', content: seoData.title });
    this.meta.updateTag({ property: 'telegram:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'telegram:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'whatsapp:title', content: seoData.title });
    this.meta.updateTag({ property: 'whatsapp:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'whatsapp:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'reddit:title', content: seoData.title });
    this.meta.updateTag({ property: 'reddit:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'reddit:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'tumblr:title', content: seoData.title });
    this.meta.updateTag({ property: 'tumblr:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'tumblr:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'slack:title', content: seoData.title });
    this.meta.updateTag({ property: 'slack:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'slack:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'skype:title', content: seoData.title });
    this.meta.updateTag({ property: 'skype:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'skype:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'line:title', content: seoData.title });
    this.meta.updateTag({ property: 'line:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'line:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'weibo:title', content: seoData.title });
    this.meta.updateTag({ property: 'weibo:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'weibo:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'qzone:title', content: seoData.title });
    this.meta.updateTag({ property: 'qzone:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'qzone:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'douban:title', content: seoData.title });
    this.meta.updateTag({ property: 'douban:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'douban:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'baidu:title', content: seoData.title });
    this.meta.updateTag({ property: 'baidu:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'baidu:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'yahoo:title', content: seoData.title });
    this.meta.updateTag({ property: 'yahoo:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'yahoo:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'ask:title', content: seoData.title });
    this.meta.updateTag({ property: 'ask:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'ask:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'aol:title', content: seoData.title });
    this.meta.updateTag({ property: 'aol:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'aol:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'excite:title', content: seoData.title });
    this.meta.updateTag({ property: 'excite:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'excite:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'lycos:title', content: seoData.title });
    this.meta.updateTag({ property: 'lycos:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'lycos:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'altitude:title', content: seoData.title });
    this.meta.updateTag({ property: 'altitude:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'altitude:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'seznam:title', content: seoData.title });
    this.meta.updateTag({ property: 'seznam:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'seznam:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'naver:title', content: seoData.title });
    this.meta.updateTag({ property: 'naver:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'naver:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'daum:title', content: seoData.title });
    this.meta.updateTag({ property: 'daum:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'daum:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'sogou:title', content: seoData.title });
    this.meta.updateTag({ property: 'sogou:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'sogou:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'shenma:title', content: seoData.title });
    this.meta.updateTag({ property: 'shenma:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'shenma:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: '360:title', content: seoData.title });
    this.meta.updateTag({ property: '360:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: '360:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'soso:title', content: seoData.title });
    this.meta.updateTag({ property: 'soso:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'soso:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'youdao:title', content: seoData.title });
    this.meta.updateTag({ property: 'youdao:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'youdao:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'sm:title', content: seoData.title });
    this.meta.updateTag({ property: 'sm:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'sm:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'safebrowsing:title', content: seoData.title });
    this.meta.updateTag({ property: 'safebrowsing:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'safebrowsing:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'malwarebytes:title', content: seoData.title });
    this.meta.updateTag({ property: 'malwarebytes:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'malwarebytes:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'norton:title', content: seoData.title });
    this.meta.updateTag({ property: 'norton:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'norton:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'mcafee:title', content: seoData.title });
    this.meta.updateTag({ property: 'mcafee:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'mcafee:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'kaspersky:title', content: seoData.title });
    this.meta.updateTag({ property: 'kaspersky:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'kaspersky:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'avg:title', content: seoData.title });
    this.meta.updateTag({ property: 'avg:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'avg:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'avast:title', content: seoData.title });
    this.meta.updateTag({ property: 'avast:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'avast:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'trendmicro:title', content: seoData.title });
    this.meta.updateTag({ property: 'trendmicro:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'trendmicro:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bitdefender:title', content: seoData.title });
    this.meta.updateTag({ property: 'bitdefender:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bitdefender:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'f-secure:title', content: seoData.title });
    this.meta.updateTag({ property: 'f-secure:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'f-secure:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'webroot:title', content: seoData.title });
    this.meta.updateTag({ property: 'webroot:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'webroot:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'comodo:title', content: seoData.title });
    this.meta.updateTag({ property: 'comodo:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'comodo:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'zonealarm:title', content: seoData.title });
    this.meta.updateTag({ property: 'zonealarm:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'zonealarm:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'panda:title', content: seoData.title });
    this.meta.updateTag({ property: 'panda:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'panda:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bullguard:title', content: seoData.title });
    this.meta.updateTag({ property: 'bullguard:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bullguard:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'sophos:title', content: seoData.title });
    this.meta.updateTag({ property: 'sophos:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'sophos:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'websense:title', content: seoData.title });
    this.meta.updateTag({ property: 'websense:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'websense:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'barkly:title', content: seoData.title });
    this.meta.updateTag({ property: 'barkly:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'barkly:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'cylance:title', content: seoData.title });
    this.meta.updateTag({ property: 'cylance:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'cylance:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'carbonblack:title', content: seoData.title });
    this.meta.updateTag({ property: 'carbonblack:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'carbonblack:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'fireeye:title', content: seoData.title });
    this.meta.updateTag({ property: 'fireeye:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'fireeye:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'lookout:title', content: seoData.title });
    this.meta.updateTag({ property: 'lookout:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'lookout:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'malwaredomainlist:title', content: seoData.title });
    this.meta.updateTag({ property: 'malwaredomainlist:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'malwaredomainlist:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'phishtank:title', content: seoData.title });
    this.meta.updateTag({ property: 'phishtank:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'phishtank:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'spamhaus:title', content: seoData.title });
    this.meta.updateTag({ property: 'spamhaus:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'spamhaus:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'urlscan:title', content: seoData.title });
    this.meta.updateTag({ property: 'urlscan:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'urlscan:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'virustotal:title', content: seoData.title });
    this.meta.updateTag({ property: 'virustotal:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'virustotal:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'hybrid-analysis:title', content: seoData.title });
    this.meta.updateTag({ property: 'hybrid-analysis:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'hybrid-analysis:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'any-run:title', content: seoData.title });
    this.meta.updateTag({ property: 'any-run:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'any-run:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'joe-security:title', content: seoData.title });
    this.meta.updateTag({ property: 'joe-security:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'joe-security:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'cisco-talos:title', content: seoData.title });
    this.meta.updateTag({ property: 'cisco-talos:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'cisco-talos:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'palo-alto:title', content: seoData.title });
    this.meta.updateTag({ property: 'palo-alto:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'palo-alto:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'fortinet:title', content: seoData.title });
    this.meta.updateTag({ property: 'fortinet:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'fortinet:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'checkpoint:title', content: seoData.title });
    this.meta.updateTag({ property: 'checkpoint:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'checkpoint:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'juniper:title', content: seoData.title });
    this.meta.updateTag({ property: 'juniper:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'juniper:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'sonicwall:title', content: seoData.title });
    this.meta.updateTag({ property: 'sonicwall:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'sonicwall:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'watchguard:title', content: seoData.title });
    this.meta.updateTag({ property: 'watchguard:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'watchguard:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'untangle:title', content: seoData.title });
    this.meta.updateTag({ property: 'untangle:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'untangle:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'sophos-xg:title', content: seoData.title });
    this.meta.updateTag({ property: 'sophos-xg:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'sophos-xg:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'pfsense:title', content: seoData.title });
    this.meta.updateTag({ property: 'pfsense:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'pfsense:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'opendns:title', content: seoData.title });
    this.meta.updateTag({ property: 'opendns:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'opendns:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'cleanbrowsing:title', content: seoData.title });
    this.meta.updateTag({ property: 'cleanbrowsing:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'cleanbrowsing:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'adguard:title', content: seoData.title });
    this.meta.updateTag({ property: 'adguard:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'adguard:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bluetack:title', content: seoData.title });
    this.meta.updateTag({ property: 'bluetack:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bluetack:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'flickr:title', content: seoData.title });
    this.meta.updateTag({ property: 'flickr:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'flickr:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'youtube:title', content: seoData.title });
    this.meta.updateTag({ property: 'youtube:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'youtube:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'vimeo:title', content: seoData.title });
    this.meta.updateTag({ property: 'vimeo:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'vimeo:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'dailymotion:title', content: seoData.title });
    this.meta.updateTag({ property: 'dailymotion:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'dailymotion:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'metacafe:title', content: seoData.title });
    this.meta.updateTag({ property: 'metacafe:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'metacafe:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'vevo:title', content: seoData.title });
    this.meta.updateTag({ property: 'vevo:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'vevo:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'twitch:title', content: seoData.title });
    this.meta.updateTag({ property: 'twitch:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'twitch:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'spotify:title', content: seoData.title });
    this.meta.updateTag({ property: 'spotify:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'spotify:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'apple-music:title', content: seoData.title });
    this.meta.updateTag({ property: 'apple-music:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'apple-music:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'soundcloud:title', content: seoData.title });
    this.meta.updateTag({ property: 'soundcloud:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'soundcloud:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bandcamp:title', content: seoData.title });
    this.meta.updateTag({ property: 'bandcamp:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bandcamp:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'mixcloud:title', content: seoData.title });
    this.meta.updateTag({ property: 'mixcloud:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'mixcloud:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'hearthis:title', content: seoData.title });
    this.meta.updateTag({ property: 'hearthis:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'hearthis:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'audiomack:title', content: seoData.title });
    this.meta.updateTag({ property: 'audiomack:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'audiomack:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'tidal:title', content: seoData.title });
    this.meta.updateTag({ property: 'tidal:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'tidal:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'deezer:title', content: seoData.title });
    this.meta.updateTag({ property: 'deezer:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'deezer:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'pandora:title', content: seoData.title });
    this.meta.updateTag({ property: 'pandora:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'pandora:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'iheartradio:title', content: seoData.title });
    this.meta.updateTag({ property: 'iheartradio:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'iheartradio:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'audible:title', content: seoData.title });
    this.meta.updateTag({ property: 'audible:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'audible:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'goodreads:title', content: seoData.title });
    this.meta.updateTag({ property: 'goodreads:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'goodreads:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'librarything:title', content: seoData.title });
    this.meta.updateTag({ property: 'librarything:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'librarything:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bookbub:title', content: seoData.title });
    this.meta.updateTag({ property: 'bookbub:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bookbub:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'scribd:title', content: seoData.title });
    this.meta.updateTag({ property: 'scribd:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'scribd:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'wattpad:title', content: seoData.title });
    this.meta.updateTag({ property: 'wattpad:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'wattpad:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'medium:title', content: seoData.title });
    this.meta.updateTag({ property: 'medium:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'medium:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'wordpress:title', content: seoData.title });
    this.meta.updateTag({ property: 'wordpress:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'wordpress:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'blogger:title', content: seoData.title });
    this.meta.updateTag({ property: 'blogger:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'blogger:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'tumblr-blog:title', content: seoData.title });
    this.meta.updateTag({ property: 'tumblr-blog:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'tumblr-blog:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'weebly:title', content: seoData.title });
    this.meta.updateTag({ property: 'weebly:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'weebly:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'wix:title', content: seoData.title });
    this.meta.updateTag({ property: 'wix:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'wix:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'squarespace:title', content: seoData.title });
    this.meta.updateTag({ property: 'squarespace:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'squarespace:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'shopify:title', content: seoData.title });
    this.meta.updateTag({ property: 'shopify:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'shopify:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bigcommerce:title', content: seoData.title });
    this.meta.updateTag({ property: 'bigcommerce:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bigcommerce:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'magento:title', content: seoData.title });
    this.meta.updateTag({ property: 'magento:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'magento:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'woocommerce:title', content: seoData.title });
    this.meta.updateTag({ property: 'woocommerce:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'woocommerce:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'prestashop:title', content: seoData.title });
    this.meta.updateTag({ property: 'prestashop:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'prestashop:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'opencart:title', content: seoData.title });
    this.meta.updateTag({ property: 'opencart:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'opencart:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'volusion:title', content: seoData.title });
    this.meta.updateTag({ property: 'volusion:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'volusion:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: '3dcart:title', content: seoData.title });
    this.meta.updateTag({ property: '3dcart:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: '3dcart:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'bigcartel:title', content: seoData.title });
    this.meta.updateTag({ property: 'bigcartel:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'bigcartel:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'gumroad:title', content: seoData.title });
    this.meta.updateTag({ property: 'gumroad:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'gumroad:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'sellfy:title', content: seoData.title });
    this.meta.updateTag({ property: 'sellfy:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'sellfy:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'itch.io:title', content: seoData.title });
    this.meta.updateTag({ property: 'itch.io:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'itch.io:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'patreon:title', content: seoData.title });
    this.meta.updateTag({ property: 'patreon:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'patreon:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'ko-fi:title', content: seoData.title });
    this.meta.updateTag({ property: 'ko-fi:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'ko-fi:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'buymeacoffee:title', content: seoData.title });
    this.meta.updateTag({ property: 'buymeacoffee:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'buymeacoffee:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'substack:title', content: seoData.title });
    this.meta.updateTag({ property: 'substack:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'substack:image', content: seoData.image || this.defaultImage });
    this.meta.updateTag({ property: 'ghost:title', content: seoData.title });
    this.meta.updateTag({ property: 'ghost:description', content: seoData.description || this.defaultDescription });
    this.meta.updateTag({ property: 'ghost:image', content: seoData.image || this.defaultImage });
  }
}